  apiRules:
  - exclude:
      uidRegex: ^System\.Object
      type: Type
  - exclude:
      uidRegex: ^System\.IO\.Stream
      type: Type
  - exclude:
      uidRegex: ^System\.MarshalByRefObject
      type: Type
  - exclude:
      uidRegex: ^DotQuic\.Endpoint
      type: Class
  - exclude:
      uidRegex: ^DotQuic\.WaitHandleExtensions.
      type: Class
  - exclude:
      uidRegex: ^DotQuic\.QuicStream\.Seek
      type: Method
  - exclude:
      uidRegex: ^DotQuic\.QuicStream\.Flush
      type: Method
  - exclude:
      uidRegex: ^DotQuic\.QuicStream\.SetLength
      type: Method
  - exclude:
      uidRegex: ^DotQuic\.QuicStream\.SetReadable
      type: Method
  - exclude:
      uidRegex: ^DotQuic\.QuicStream\.SetWritable
      type: Method
  - exclude:
      uidRegex: ^DotQuic\.QuicStream\.Length
      type: Property
  - exclude:
      uidRegex: ^DotQuic\.QuicStream\.Position
      type: Property
  - exclude:
      uidRegex: ^DotQuic\.QuicStream\.CanSeek
      type: Property